- name: Generate values.yaml for Longhorn
  template:
    src: values.j2
    dest: /tmp/longhorn-values.yaml

- name: Install Longhorn
  shell: | 
    helm repo add longhorn https://charts.longhorn.io
    helm repo update
    helm install longhorn longhorn/longhorn \
    --namespace longhorn-system \
    --version "{{ longhorn.version }}" \
    --create-namespace \
    --values /tmp/longhorn-values.yaml
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
