- name: Get the default network interface
  set_fact:
    internal_interface: "{{ ansible_default_ipv4.interface }}"

- name: Flush existing iptables rules
  command:
    cmd: "iptables -F"

- name: Flush existing NAT table rules
  command:
    cmd: "iptables -t nat -F"

- name: Forward traffic to specified ports
  command:
    cmd: "iptables -t nat -A PREROUTING -p {{ item.1.proto }} --dport {{ item.1.src }} -j DNAT --to-destination {{ item.0.destination_lb_ip }}:{{ item.1.dest }}"
  loop: "{{ external_connection.entrypoints | subelements('forward_ports') }}"

- name: Allow forward traffic from WireGuard interface to internal network
  command:
    cmd: "iptables -A FORWARD -i {{ external_connection.wireguard_interface }} -o {{ internal_interface }} -p {{ item.1.proto }} {% if item.1.proto == 'tcp' %}--syn {% endif %} --dport {{ item.1.dest }} -m conntrack --ctstate NEW -j ACCEPT"
  loop: "{{ external_connection.entrypoints | subelements('forward_ports') }}"

- name: Handle return traffic with MASQUERADE for WireGuard interface
  command:
    cmd: "iptables -t nat -A POSTROUTING -o {{ external_connection.wireguard_interface }} -j MASQUERADE"

- name: Handle return traffic with MASQUERADE for internal network
  command:
    cmd: "iptables -t nat -A POSTROUTING -o {{ internal_interface }} -j MASQUERADE"

- name: Save iptables rules
  command:
    cmd: "netfilter-persistent save"
