##############
# k8s
##############
[master_nodes]
k8s-master-node ansible_host=home-k8s-master ansible_user=root ip_address=192.168.1.111

[worker_nodes]
k8s-worker-node-1 ansible_host=home-k8s-worker-1 ansible_user=root node_labels="['cpu=intel', 'size=medium']"
k8s-worker-node-2 ansible_host=home-k8s-worker-2 ansible_user=root node_labels="['cpu=amd', 'size=large']"

[entrypoint_nodes]
k8s-entrypoint-internal ansible_host=home-k8s-entrypoint-internal ansible_user=root ip_address=192.168.1.101
k8s-entrypoint-external ansible_host=home-k8s-entrypoint-external ansible_user=root ip_address=116.203.72.4

##############
# RPI
##############
[rpi_cluster]
home-r1 ansible_host=home-r1 ip_address=192.168.1.21 keepalived_state=MASTER keepalived_priority=101 vault_node_id=node1 vault_api_addr=https://vault1.us2h.home:8200
home-r2 ansible_host=home-r2 ip_address=192.168.1.22 keepalived_state=BACKUP keepalived_priority=100 vault_node_id=node2 vault_api_addr=https://vault2.us2h.home:8200
home-r3 ansible_host=home-r3 ip_address=192.168.1.23 keepalived_state=BACKUP keepalived_priority=100 vault_node_id=node3 vault_api_addr=https://vault3.us2h.home:8200
