- name: Generate values.yaml for Metallb
  template:
    src: values.j2
    dest: /tmp/metallb-values.yaml

- name: Install MetalLB
  shell: | 
    helm repo add metallb https://metallb.github.io/metallb
    helm repo update
    helm install metallb metallb/metallb \
    --namespace metallb-system \
    --version "{{ metallb.version }}" \
    --create-namespace \
    -f /tmp/metallb-values.yaml
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
