kubernetes_version: 1.33
kubernetes_pod_network: "10.244.0.0/16"

helm:
  version: 3.17.0

ha:
  enabled: false
  stats_login: admin
  stats_password: password

control_plane_address: "{% if ha.enabled %}{{ hostvars[groups['master_lb'][0]].ip_address }}{% else %}{{ hostvars[groups['master_nodes'][0]].ip_address }}{% endif %}"

metallb:
  version: 0.14.9
  address: 192.168.1.201/32

cert_manager:
  version: 1.17.2
  letsencrypt_email: us2h@mm.st

longhorn:
  version: 1.8.1
  data_path: /mnt/disk

fluxcd:
  enabled: true
  repository: ssh://git@github.com/us2h/home-k8s.git
  branch: master
